FROM ubuntu:16.04

LABEL Description="MEICAN Image" \
      Author="Leonardo Lauryel Batista dos Santos"

ARG MEICAN_VERSION \ 
   DEBIAN_FRONTEND=noninteractive \
   DEBCONF_NONINTERACTIVE_SEEN=true

ENV MYSQL_DATABASE=$MYSQL_DATABASE \
   MYSQL_USER=$MYSQL_USER \
   MYSQL_PASSWORD=$MYSQL_PASSWORD \
   MEICAN_DIR=/home/meican/meican-$MEICAN_VERSION
   
RUN apt-get update \
 && apt-get install -yq --no-install-recommends \
    apt-utils \
    curl \
    sudo \
    zip \
    unzip \
    # Install apache
    apache2 \
    # Install php 7.0
    php7.0 \
    php7.0-mysql \
    php7.0-mbstring \
    php7.0-curl \
    php7.0-soap \
    php7.0-xml \
    libapache2-mod-php \
 && rm -rf /var/lib/apt/lists/*

RUN adduser --disabled-password --gecos '' meican \
 && usermod -aG sudo meican

RUN curl -k0 https://getcomposer.org/download/2.2.23/composer.phar -o /usr/local/bin/composer \
 && chmod +x /usr/local/bin/composer \
 && ln -s $MEICAN_DIR/web /var/www/meican \
 && a2enmod rewrite

WORKDIR $MEICAN_DIR

COPY 000-default.conf /etc/apache2/sites-available/

COPY docker-entrypoint.sh /

EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.sh"]
